### ISSUE TITLE
Why bignums?

### ISSUE THREAD

**Issue by Athas** [clarkzjw/one-two-three...infinity#23]
The sum of counting to a billion is a mere 500000000500000000, which fits easily in a 64-bit integer (even with a bit or two taken away for GC purposes).  So is there a particular reason why so many of the implementations use arbitrary-sized integer types?

**Comment by wRadion** [comment]
@Athas Good point.

Also, running most (all?) of these would take a very long time to process, so we can't test them right away and find the most efficient very easily. I don't know if this is part of the project, but this could be great to compare code length and actual execution time of each programs (and maybe memory management if you still want to go with bignums) :) .

**Comment by JinweiClarkChao** [comment]
Hi, @Athas and @wRadion . Thank you for your interest in this project.

To be honest, when I started this project in 2014, I was inspired by https://github.com/leachim6/hello-world/issues/158 . The initial purpose is just for fun, or just something more complex than Hello-World. 

Taking execution time and memory management into consideration is a good point. The testing environment might be a little complex to set up,  because there are so many different languages. 

Any more good advises ?  :smile:

**Comment by wRadion** [comment]
@JinweiClarkChao
Well, for interpreted languages that can be easy. You just install each interpreter and run with Unix's `time` command: `time {interpreter} sum.{lang}` for each languages. `time` will then measure the real/user execution time and you could easily display that on an HTML page.

But for compiled language, that's another story. You have to compile each program then run it, but some language won't compile on a specific system and that could be a real mess. But it's still possible.

And for measuring memory management, I don't really know tools that can do that so easily.
